hofvidz/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.urls import path
from halls import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),

    # AUTH
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),

    # HALL
    path('halloffame/create', views.CreateHall.as_view(), name='create_hall'),
    path('halloffame/<int:pk>', views.DetailHall.as_view(), name='detail_hall'),
    path('halloffame/<int:pk>/update', views.UpdateHall.as_view(), name='update_hall'),
    path('halloffame/<int:pk>/delete', views.DeleteHall.as_view(), name='delete_hall'),

    # Video
    path('halloffame/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video')

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

halls/models.py
from django.db import models
from django.contrib.auth.models import User


class Hall(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

halls/forms.py
from django import forms
from .models import Video


# model Form
class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url': 'Youtube Url'}


# django forms
class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Search for Videos')

halls/views.py
from django.shortcuts import render, redirect, Http404
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from .models import Hall, Video
from django.contrib.auth import authenticate, login
from .forms import VideoForm, SearchForm
from django.http import Http404, JsonResponse
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from urllib.parse import urlparse
import requests


YOUTUBE_API_KEY = 'AIzaSyDHYyX8cUL1P35PZeSEBEha2IQtQ9tgDa4'


def home(request):
    recent_halls = Hall.objects.all().order_by('-id')[:3]
    popular_halls = [Hall.objects.get(pk=1), Hall.objects.get(pk=2), Hall.objects.get(pk=3)]
    return render(request, 'halls/home.html', {'recent_halls': recent_halls, 'popular_halls': popular_halls})


@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user)
    return render(request, 'halls/dashboard.html', {'halls': halls})


@login_required
def add_video(request, pk):
    # VideoFormSet = formset_factory(VideoForm, extra=5)
    # form = VideoFormSet()
    form = VideoForm()
    search_form = SearchForm()
    hall = Hall.objects.get(pk=pk)
    if not hall.user == request.user:
        raise Http404

    if request.method == 'POST':
        # create

        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.hall = hall
            video.url = form.cleaned_data['url']
            parsed_url = urlparse(video.url)
            url_query = parsed_url.query
            video_id = url_query.replace('v=', '')
            if video_id:
                video.youtube_id = video_id
                response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id}&key={YOUTUBE_API_KEY}')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.save()
                return redirect('detail_hall', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Needs to be a YouTube Url')
    return render(request, 'halls/add_video.html', {'form': form, 'search_form': search_form, 'hall': hall})


@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        search_term = search_form.cleaned_data['search_term']
        print(search_term)
        response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q={ search_term }&key={YOUTUBE_API_KEY}')
        return JsonResponse(response.json())
    return JsonResponse({'error': 'Not able to validate form'})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


# CRUD
class CreateHall(LoginRequiredMixin, generic.CreateView):
    model = Hall
    fields = ['title']
    template_name = 'halls/create_hall.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateHall, self).form_valid(form)
        return redirect('dashboard')


class DetailHall(generic.DetailView):
    model = Hall
    template_name = 'halls/detail_hall.html'


class UpdateHall(LoginRequiredMixin, generic.UpdateView):
    model = Hall
    template_name = 'halls/update_hall.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(UpdateHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall


class DeleteHall(LoginRequiredMixin, generic.DeleteView):
    model = Hall
    template_name = 'halls/delete_hall.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(DeleteHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall


class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name = 'halls/delete_video.html'
    success_url = reverse_lazy('dashboard')

    # Ensure that you delete only videos you created
    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.hall.user == self.request.user:
            raise Http404
        return video

halls/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cyborg/bootstrap.min.css">

    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static "custom.css" %}">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <title>{% block title %}
    
    {% endblock %} Hall of Fame Vidz</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand text-danger" href="{% url 'home' %}">Hall of Fame Videos</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item p-2">
            <a class="nav-link " href="{% url 'dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item p-2">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item p-2">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        {% if user.is_authenticated == False %}
        <li class="nav-item p-2">
            <a class="btn btn-outline-danger" href="{% url 'signup' %}">Sign Up</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


        {% block content %}
        
        {% endblock %}
        


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

halls/templates/halls/add_video.html
{% extends "base.html" %}

{% block title %}
    Add video - {{ block.super }}
{% endblock %}

{% block content %}
<div class="container">
    <h3>Add Video to {{ hall.title }}</h3>
    <div class="row">
        <div class="col-md-8">
        <form method="post" id="submit_video">
            {% csrf_token %}
            {% load widget_tweaks %}
            {% for field in form %}
            <div class="form-group py-1 {% if field.errors %} alert alert-danger {% endif %}">
                {{ field.errors }}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}
    {#        {% for field in form %}#}
    {#            <p>#}
    {#            {{ field.errors }}#}
    {#            {{ field.label_tag }}#}
    {#            {{ field }}#}
    {#            </p>#}
    {#        {% endfor %}#}

            <button type="submit" class="btn btn-danger">Add Video</button>
        </form>
        </div>
    </div>
    <br>
    <h4>Or</h4>
    <div class="row">
        <div class="col-md-8">
            <form>
                {% for field in search_form%}
                <div class="form-group py-1 {% if field.errors %} alert alert-danger {% endif %}">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                </div>
                {% endfor %}
            </form>
        </div>
    </div>

    <div id="search_results"></div>
    <script>
        var delayTimer;
        $('#id_search_term').keyup(function () {
           clearTimeout(delayTimer);
           $('#search_results').text('Loading.....');
           delayTimer = setTimeout(function () {
               var text = $('#id_search_term').val();
               $.ajax({
                   url: '/video/search',
                   data: {
                       'search_term': text
                   },
                   dataType: 'json',
                   success: function (data) {

                       var results = '';
                       $('#search_results').text('');
                       results += '<div class="row">';

                       data['items'].forEach(function(video) {
                          results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                          results += '<iframe width="100%" height="200" src="https://www.youtube.com/embed/'+ video['id']['videoId'] +
                              '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                          results += '<div class="card-body"><p class="card-text">'+ video['snippet']['title'] +'</p>';
                          results += '<a href="#" class="btn btn-danger" onclick="addVideo(\''+ video['id']['videoId']+'\')">Add</a>';
                          results += '</div></div></div>';

                       });
                       results += '</div>';
                       $('#search_results').append(results)
                   }
               });
           }, 1000);
        });

        function addVideo(video_id) {
           $('#id_url').val('https://www.youtube.com/watch?v='+ video_id);
           $('#submit_video').submit();

        }

    </script>
</div>
{% endblock %}

halls/templates/halls/create_hall.html
{% extends "base.html" %}

{% block title %}
    Create Hall - {{ block.super }}
{% endblock %}

{% block content %}
<div class="container">
    <h3>Create Hall</h3>
    <div class="row">
        <div class="col-md-8">
            <form method="post">
                {% csrf_token %}
{#                {{ form.as_p }}#}
                {% load widget_tweaks %}
                {% for field in form %}
                    <div class="form-group py-1 {% if field.errors %} alert alert-danger {% endif %}">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {% render_field field class="form-control" %}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-danger">Create Hall</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

halls/templates/halls/dashboard.html
{% extends "base.html" %}

{% block title %}
    Dashboard - {{ block.super }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="text-center py-2">
        <h3>{{ user.username }}'s Hall of Fame</h3>
        <a href="{% url 'create_hall' %}" class="btn btn-danger"> Create New Hall of Fame </a>
    </div>
        {% for hall in halls %}
{#            {% if hall.video_set.all %}#}
                <h4><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h4>
                <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger"> Delete Hall </a>
                <a href="{% url 'update_hall' hall.id  %}" class="btn btn-warning"> Edit Hall</a>
                <a href="{% url 'add_video' hall.id  %}" class="btn btn-primary"> Add Video</a>
{#            {% endif %}#}


        <div class="row">
            {% for video in hall.video_set.all %}
                <div class="col-md-4 mt-3">
                    <div class="card mb-4 shadow-sm">
                        <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <div class="card-body">
                    <p class="card-text">{{video.title}}</p>
                </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}


</div>
{% endblock %}

halls/templates/halls/delete_hall.html
{% extends "base.html" %}

{% block title %}
    Delete Hall - {{ block.super }}
{% endblock %}

{% block content %}
<div class="container">
    <h5>Are you sure you want to delete this hall of fame?</h5>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    <br>
    <h5><a href="{% url 'detail_hall' hall.id %}">{{hall.title}}</a></h5>
</div>
{% endblock %}

halls/templates/halls/delete_video.html
{% extends "base.html" %}

{% block title %}
    Delete Video - {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container">
        <h5>Are you sure you want to delete this video?</h5>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
        <br>
        <div class="row">
           <div class="col-md-4 mt-3">
               <div class="card mb-4 shadow-sm">'
                    <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <div class="card-body">
                        <p class="card-text">{{video.title}}</p>
                    </div>
               </div>
           </div>
       </div>

    </div>

{% endblock %}

halls/templates/halls/detail_hall.html
{% extends "base.html" %}

{% block title %}
    {{ hall.title }} - {{ block.super }}
{% endblock %}

{% block content %}
<div class="container">
    <h4>{{ hall.title }}</h4>
    <h4 class="text text-muted">{{ hall.user.username }}</h4>

    {% if user.id == hall.user.id %}
        <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger"> Delete Hall </a>
        <a href="{% url 'update_hall' hall.id  %}" class="btn btn-warning"> Edit Hall</a>
        <a href="{% url 'add_video' hall.id  %}" class="btn btn-primary"> Add Video</a>
    {% endif %}
        <div class="row">
            {% for video in hall.video_set.all %}
                <div class="col-md-4 mt-3">
                    <div class="card mb-4 shadow-sm">
                        <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <div class="card-body">
                    <p class="card-text">{{video.title}}</p>
                        {% if user.id == hall.user.id %}
                             <a href="{% url 'delete_video' video.id  %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                </div>
                </div>
            </div>
            {% endfor %}
        </div>
</div>
{% endblock %}

halls/templates/halls/home.html
{% extends "base.html" %}

{% block title %}
    Home - {{ block.super }}
{% endblock %}

{% block content %}

    <section class="jumbotron bg-dark" style="border-radius: 0">
        <div class="container text-center">
            <h4 class="jumbotron-heading text-danger">What's your personal Hall of Fame?</h4>
            <p class="lead text-muted">You know what they are. They are your favorite videos. You have your top 10 list and it's time to share them with the world. Click the button below to get started.</p>
            <hr class="my-4">
            <p>
                <a href="{% url 'create_hall' %}" class="btn btn-danger">Create your Hall of fame</a>
            </p>
        </div>
    </section>
    <div class="container">
        <h3 class="text-center">Popular Hall of Fame</h3>
        {% for popular_hall in popular_halls %}
            <h4><a href="{% url 'detail_hall' popular_hall.id %}">{{ popular_hall.title }}</a></h4>
            <div class="row">
            {% for video in popular_hall.video_set.all %}
                <div class="col-md-4 mt-3">
                    <div class="card mb-4 shadow-sm">
                        <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <div class="card-body">
                            <p class="card-text">{{video.title}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>

        {% endfor %}

    <h3 class="text-center">Recent Hall of Fame</h3>
        {% for recent_hall in recent_halls %}
            <h4><a href="{% url 'detail_hall' recent_hall.id %}">{{ recent_hall.title }}</a></h4>
            <div class="row">
            {% for video in recent_hall.video_set.all %}
                <div class="col-md-4 mt-3">
                    <div class="card mb-4 shadow-sm">
                        <iframe width="100%" height="200" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <div class="card-body">
                            <p class="card-text">{{video.title}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>

        {% endfor %}

    </div>
{% endblock %}

halls/templates/halls/update_hall.html
{% extends "base.html" %}

{% block title %}
    Create Hall - {{ block.super }}
{% endblock %}

{% block content %}
 <div class="container">
    <h3>Edit Hall</h3>
    <div class="row">
        <div class="col-md-8">
            <form method="post">
                {% csrf_token %}
                {% load widget_tweaks %}
                    {% for field in form %}
                    <div class="form-group py-1 {% if field.errors %} alert alert-danger {% endif %}">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {% render_field field class="form-control" %}
                    </div>
                    {% endfor %}
                <button type="submit" class="btn btn-warning">Save Hall</button>
            </form>
        </div>
    </div>
    <br>
    <h2><a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger">Delete this Hall of Fame</a></h2>
 </div>
{% endblock %}